name: Install
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 25.x
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Bun
        run: bun i --no-save
      - name: Palabra Install
        run: bun bin/palabra.js install `bun bin/palabra.js list`
      - name: Palabra Run
        run: eval `bun scripts/run-all-bin.js`
