name: Build rizin

on:
  push:
    tags:
      - '*'

env:
  RIZIN_VERSION: 0.9.0

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            arch: amd64
          - runner: ubuntu-24.04-arm
            arch: aarch64

    runs-on: ${{ matrix.runner }}

    permissions:
      contents: write

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build pkg-config python3-pip
          pip install meson --break-system-packages

      - name: Clone rizin
        run: |
          git clone --depth 1 --branch v${{ env.RIZIN_VERSION }} https://github.com/rizinorg/rizin.git

      - name: Build
        run: |
          cd rizin
          meson setup build \
            --buildtype=release \
            --default-library=static \
            --prefix=/tmp/rizin-out \
            -Dstatic_runtime=true \
            -Dblob=true
          ninja -C build
          ninja -C build install

      - name: Package
        run: |
          tar cJf rizin-${{ env.RIZIN_VERSION }}-linux-${{ matrix.arch }}.tar.xz -C /tmp/rizin-out .

      - name: Create release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          files: rizin-${{ env.RIZIN_VERSION }}-linux-${{ matrix.arch }}.tar.xz